### ISSUE TITLE
[REQUEST] Assigned but Unused Variable Error when Variable is Used in ERB

### ISSUE THREAD

**Issue by weilandia** [AtomLinter/linter-ruby#58]
Would it be possible to not trigger the 'assigned but unused variable' error when the variable in question is being called in an erb file?

Example:
![syntax_error_with_erb](https://cloud.githubusercontent.com/assets/13652979/12224034/517302aa-b7a4-11e5-9d6a-26e5988159b2.jpg)

<img width="516" alt="screen shot 2016-01-10 at 2 10 28 pm" src="https://cloud.githubusercontent.com/assets/13652979/12224036/5c1cd78a-b7a4-11e5-89c8-9e894f688f07.png">

Thanks!

**Comment by Arcanemagus** [comment]
This package is simply an interface to running `ruby -wc` on the file, I'm not actually sure where you would file this to have the people working on Ruby look into this, but I don't think there is anything that can be done.

Unless you know of a way to run Ruby's checker that has it check external files?

**Comment by JoshCheek** [comment]
You can probably just remove the `w` from here https://github.com/AtomLinter/linter-ruby/blob/9507caa353de0672c3a3566c396911f52daf51da/lib/main.js#L43 The "w" means "warning" which is only useful if you're sloppy with your code eg `a +b` because there is whitespace on one side and not the other will parse to `a(+b)` but was probably intended to be `a.+(b)` The package will be in ~/.atom/packages/linter-ruby, edit it by hand to see if it works and if you like it. If so, you can keep it and move on with life, or submit a pull request that moves it into the configuration.

Alternatively, it's uncommon to pass local variables to an ERB template (guessing you have `ERB.new(template).result(binding)` down below... which implies the code isn't going to work, since those variables are getting set in the binding of the `each` block, which goes away after line 45). It's more common to use instance variables, or render in the context of some view object.

**Comment by weilandia** [comment]
Issue can be resolved by writing better ruby... Thanks!

**Comment by weilandia** [comment]
Issue can be resolved by writing better ruby... Thanks!
